services:
  typescript-app:
    container_name: typescript-app
    build:
      context: .
      dockerfile: Dockerfile
    # env_file: ./.env  # Uncomment if .env file exists
    ports:
      - "3000:3000"  # Expose the application port as defined in Dockerfile
    restart: unless-stopped
    init: true
    networks:
      - app-network
    # If you add a database or other services, add 'depends_on' here

# Network for inter-service communication
networks:
  app-network:
    driver: bridge
